apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.1.0
    component: master
    release: elasticsearch
  name: elasticsearch-elasticsearch-discovery
  namespace: elasticsearch
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: '0.0.0.0/0'
spec:
  ports:
  - port: 9300
    protocol: TCP
    targetPort: transport
  selector:
    app: elasticsearch
    component: master
    release: elasticsearch
  type: ClusterIP
